name: Informacion de Variables de Contexto

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug,Release]
        dotnetversion: [6.0.x,7.0.x]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{matrix.dotnetversion}}
    - name: Restore dependencies
      run: dotnet restore src/wpm-api/WisdomPetMedicine.sln
    - name: Build
      run: dotnet build src/wpm-api/WisdomPetMedicine.sln --configuration ${{matrix.configuration}} --no-restore
    - name: Informacion del Job Actual
      run: echo ${{ job.status }}
    - name: Informacion de la rama
      run: echo ${{ github.ref }}
