name: .NET con Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/wpm-api/WisdomPetMedicine.sln
    - name: Build
      run: dotnet build src/wpm-api/WisdomPetMedicine.sln --no-restore
    - name: Test
      run: dotnet test src/wpm-api/WisdomPetMedicine.sln --no-build --verbosity normal
  
  docker:
    name: Dockerizacion delproyecto
    runs-on: ubuntu-lastest
    needs: [build]
    steps:
    - uses: actions/checkout@v4
    - name: dockerbuild
      run: docker build src/wpm-api --file src/wpm-api/Dockerfile --tag github-action-esencial
